version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: "sudo apt update"
      - run: "sudo apt install valgrind"
      - run: "make"
      - run: ./ste_test.sh
      - run: ./string_helpers_test
      - store_artifacts:
          path: test_outputs
