version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: "make"
      - run: ./test.sh
      - store_artifacts:
          path: test_outputs
